### ISSUE TITLE
Fix the "Developer Responsibilities" section

### ISSUE THREAD

**Issue by dimpiax** [CodeDoesGood/DevHatchery#1]
**Optional** corresponds to *Assistant Mentors* which is incorrect.
https://github.com/CodeDoesGood/DevHatchery/wiki/1.-Responsibilities#developer-responsibilities

**Comment by dimpiax** [comment]
https://github.com/CodeDoesGood/DevHatchery/wiki/1.-Responsibilities#developer-responsibilities

**Comment by abbeyjackson** [comment]
fixed
